export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
//create templates
export const CREATE_TEMPLATE_START = 'CREATE_TEMPLATE_START';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAIL = 'CREATE_TEMPLATE_FAIL';
export const CREATE_TEMPLATE_INIT = 'CREATE_TEMPLATE_INIT';
//update templates
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_FAIL = 'UPDATE_TEMPLATE_FAIL';
//fetch templates
export const FETCH_TEMPLATES_START = 'FETCH_TEMPLATES_START';
export const FETCH_TEMPLATES_SUCCESS = 'FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAIL = 'FETCH_TEMPLATES_FAIL';
//create reponses
export const CREATE_RESPONSE_START = 'CREATE_RESPONSE_START';
export const CREATE_RESPONSE_SUCCESS = 'CREATE_RESPONSE_SUCCESS';
export const CREATE_RESPONSE_FAIL = 'CREATE_RESPONSE_FAIL';
export const CREATE_RESPONSE_INIT = 'CREATE_RESPONSE_INIT';
//update responses
export const UPDATE_RESPONSE_SUCCESS = 'UPDATE_RESPONSE_SUCCESS';
export const UPDATE_RESPONSE_FAIL = 'UPDATE_RESPONSE_FAIL';
//fetch responses
export const FETCH_RESPONSES_START = 'FETCH_RESPONSES_START';
export const FETCH_RESPONSES_SUCCESS = 'FETCH_RESPONSES_SUCCESS';
export const FETCH_RESPONSES_FAIL = 'FETCH_RESPONSES_FAIL';